### ISSUE TITLE
Failure to decode some TYPE_REF due to lists not being added to p.refs

### ISSUE THREAD

**Issue by naktinis** [sollyucko/py-marshal#2]
Disclaimer: I'm new to this lib and today read `marshal.c` for the first time, so sorry if I'm missing some details.

What I did was generated a marshalled file with Python 3.9, like this:

```
$ python3
>>> import marshal
>>> data = ['a', 'a']
>>> marshal.dumps(data)
b'\xdb\x02\x00\x00\x00\xda\x01ar\x01\x00\x00\x00'
```

Trying to load this with `py-marshal` **returns an error**:
```
let obj = read::marshal_loads(b"\xdb\x02\x00\x00\x00\xda\x01ar\x01\x00\x00\x00");
println!("${:?}", obj);
```
```
$Err(Error(InvalidRef, State { next_error: None, backtrace: InternalBacktrace { backtrace: None } }))
```

However, unmarshalling the list **without a variable works just fine**:
```
$ python3
>>> import marshal
>>> marshal.dumps(['a', 'a'])
b'[\x02\x00\x00\x00\xda\x01ar\x00\x00\x00\x00'
```

```
let obj = read::marshal_loads(b"[\x02\x00\x00\x00\xda\x01ar\x00\x00\x00\x00");
println!("${:?}", obj);
```
```
$Ok(List(RwLock { data: [String("a"), String("a")] }))
```

So comparing the two marshalled values, I see two differences:
 - in the first one, the list object has FLAG_REF set
 - in the first one, the second "a" is addressed via reference `1` instead of `0` that we see in the second output
 
 ```
db02 0000 00da 0161 7201 0000 00  <- marshalled via data variable
5b02 0000 00da 0161 7200 0000 00  <- marshalled directly
^                      ^
|                      |_ (in first one) reference to 1, because list is 0
|_ (in first one) list type with FLAG_REF set
 ```

Reading the `lib.rs` I see:
```
Type::SmallTuple | Type::Tuple | Type::FrozenSet | Type::Code if flag => {
    let i = p.refs.len();
    p.refs.push(Obj::None);
    Some(i)
}
```

Which seems that only these object types get indexed beforehand (surely enough, replacing list with tuple in my first Python example fixes the issue). If I add `Type::List` to the list above, the issue disappears. If this has no side effects, then at least `Type::Dict` should also be there.

**Comment by sollyucko** [comment]
Looks like [`TYPE_SMALL_TUPLE`/`TYPE_TUPLE`](https://github.com/python/cpython/blob/master/Python/marshal.c#L1165), [`TYPE_LIST`](https://github.com/python/cpython/blob/master/Python/marshal.c#L1193), [`TYPE_DICT`](https://github.com/python/cpython/blob/master/Python/marshal.c#L1213), and [`TYPE_SET`](https://github.com/python/cpython/blob/master/Python/marshal.c#L1262) use `R_REF` before reading their contents, and [`TYPE_FROZENSET`](https://github.com/python/cpython/blob/master/Python/marshal.c#L1267) and [`TYPE_CODE`](https://github.com/python/cpython/blob/master/Python/marshal.c#L1317) use `r_ref_reserve` + `r_ref_insert` instead with similar effect. I will therefore add `Type::List`, `Type::Dict`, and `Type::Set` to that list, and add your examples as test cases. Thanks for pointing this out and figuring out what the issue might be!
